name: base9
description: "A new Flutter project."
publish_to: 'none'
version: 0.7.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  forui: ^0.17.0
  package_info_plus: ^9.0.0
  signals: ^6.3.0
  upgrader: ^12.5.0
  url_launcher: ^6.3.0
  version: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
