name: base9
description: "A new Flutter project."
publish_to: "none"
version: 0.9.4

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  forui: ^0.17.0
  http: ^1.2.0
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  signals: ^6.3.0
  version: ^3.0.2
  yaml: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_svg: ^2.0.16

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
